name: Publish to winget

on:
  release:
    types: [released]

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to winget
        uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: polrivero.GitHubDesktopPlus
          installers-regex: '\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
